# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-web-app-service
  namespace: default  # <--- ADD THIS LINE FOR SERVICE
  labels:
    app: python-web-app
spec:
  selector:
    app: python-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort # Or NodePort if LoadBalancer is not supported by Docker Desktop
