# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-web-app-service
  labels:
    app: python-web-app
spec:
  selector:
    app: python-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer # Or NodePort if LoadBalancer is not supported by Docker Desktop
